DROP TABLE IF EXISTS os_core_faqanswer;
CREATE TABLE os_core_faqanswer (
  pn_id int(6) NOT NULL auto_increment,
  pn_id_cat int(6) default NULL,
  pn_question text,
  pn_answer text,
  pn_submittedby varchar(250) NOT NULL default '',
  PRIMARY KEY  (pn_id)
) TYPE=MyISAM;

--
-- Dumping data for table `os_core_faqanswer`
--

INSERT INTO os_core_faqanswer VALUES (1,1,'What is OpenStar?','OpenStar is a value-added PostNuke distribution. Our aim is to deliver a more complete eBusiness/CMS solution while still remaining compatible to the proven core PostNuke distribution.','2');
INSERT INTO os_core_faqanswer VALUES (2,1,'What PostNuke version is OpenStar based on?','The current OpenStar release (4.02) is based on PostNuke 0.762 and is compatible with this PostNuke version.','2');
INSERT INTO os_core_faqanswer VALUES (3,1,'Will you be supporting future PostNuke versions?','Yes. We plan to upgrade OpenStar to the latest stable PostNuke release within a few weeks of the release of such a version, provided that said version proves itself to be stable.','2');
INSERT INTO os_core_faqanswer VALUES (4,1,'What are the main differences for end-users?','We have added additional functional components which cover the following areas: \r\n<ul>\r\n<li>Calendar and AddressBook (integrated)</li>\r\n<li>Media- and Contentmangement (integrated)</li>\r\n<li>Project Management (integrated with AddressBook)</li>\r\n<li>Event and Ressource Booking</li>\r\n<li>Helpdesk and Service</li>\r\n<li>and many more ...</li>\r\n</ul>\r\nYou should find OpenStar to be a more complete PostNuke with most useful 3rd party modules already installed and working.\r\n\r\n','2');
INSERT INTO os_core_faqanswer VALUES (5,1,'What are the main differences for developers? ','We provide an advanced development kit which greatly simplifies module development: \r\n<ul>\r\n<li><a href=\"index.php?module=pagesetter&func=viewpub&tid=2&pid=14&mp=/Developers/Object%20Layer\">Object Persistence Layer</a></li>\r\n<li><a href=\"index.php?module=pagesetter&func=viewpub&tid=2&pid=15&mp=/Developers/Components\">Component Architecture</a></li>\r\n<li><a href=\"index.php?module=pagesetter&func=viewpub&tid=2&pid=16&mp=/Developers/Extensions\">Integration of other 3rd party components</a></li>\r\n</ul>\r\nModule development using these methodologies is significantly faster than module development using the standard PostNuke facilities. ','2');
INSERT INTO os_core_faqanswer VALUES (6,1,'What does it cost? How is it licensed? ','Our software is available for free via download and is distributed under the GNU GPL. As such it is freely redistributable and can be reused by developers in their own projects subject to the terms of the GNU GPL. This means that modules developed on the basis of v4blib must be GPL licensed.','2');
INSERT INTO os_core_faqanswer VALUES (7,1,'Why an new distribution (rather than improving PostNuke)? Are you cooperating with the PostNuke team?','Given that PostNuke has as its goal to produce a lean and stable core engine, some of the changes we have introduced are too far-reaching to be readily incorporated into the PostNuke core. As such it makes more sense to develop OpenStar as a PostNuke add-on. When appropriate, we supply selective fixes and patches back to the PostNuke team. We would like to stress that we do <i>not intend to fork</i> PostNuke and will continue to build on it\'s proven core engine. We have spent significant effort ensuring that OpenStar remains 100% compatible to PostNuke and intend to keep it that way. You can read some of our ideas which lead to the OpenStar distribution starting <a href=\"index.php?module=pagesetter&func=viewpub&tid=2&pid=0&mp=/OpenStar/Background\">here</a>','2');
INSERT INTO os_core_faqanswer VALUES (8,1,'Do your development libraries work as advertised or are they just a new/unproven idea?','Our development libraries and components (called v4blib) are the result of our experiences writing custom modules for our customers. We have been using these abstractions in various forms for more than a year by now and have encountered no significant problems to speak of. Since they have been in use for this extended period of time, you can be quite confident that they are relatively bug-free and their existing interfaces will not change significantly anymore.','2');
INSERT INTO os_core_faqanswer VALUES (9,1,'How can I get started using your development libraries for my modules?','First of all, please take a look at the <a href=\"index.php?module=pagesetter&func=viewpub&tid=2&pid=4&mp=/Developers\">Developers</a> section on our site. It contains some basic info about the features provided by our library as well as the automatically generated documentation (which is also provided in the <i>includes/v4blib/html</i> directory of the OpenStar distribution). If this still leaves you puzzled, take a look at any of the <i>v4b</i> modules (in the <i>modules</i> directory) for some examples on how to use the features provided by our development kit. If this still leaves you puzzled, you are more than welcome to use the <a href=\"index.php?module=pnForum&func=viewforum&forum=4&mp=/Forum\">Development Forum</a> to ask your specific questions.','2');
INSERT INTO os_core_faqanswer VALUES (10,1,'What languages do you support of of the box?','We ship with all modules at least providing full English and German language support. Selective module which come from the PostNuke community may support more languages.','2');
INSERT INTO os_core_faqanswer VALUES (11,1,'How can I add support for a new language?','First of all you need to download and install the PostNuke language kit for your (new) language. Then you need to either chase down language kits for the 3rd party modules we bundle. Finally you need to translate the language files for the v4b modules to your (new) language. As you can see, this is a somewhat complicated and labor-intensive process; unfortunatey there\'s nothing that can be done about that. Contact us at the Forums and we\'ll try to guide you trough this (and help you out) as much as possible.','2');
INSERT INTO os_core_faqanswer VALUES (12,1,'How can I tell if a module was written specifically for the OpenStar platform or if it is a general PostNuke module?','If a module\'s name starts with \"v4b\", then it was written by us and uses the features provided by our development library (v4blib). Any other module can be assumed to be written for the general PostNuke platform.','2');
INSERT INTO os_core_faqanswer VALUES (20,4,'Was ist OpenStar? ','OpenStar ist eine erweiterte PostNuke Distribution. Es ist unser erklärtes Ziel, eine komplettere eBusiness/CMS Lösung zu erstellen, jedoch kompatibel zu PostNuke zu bleiben. ','2');
INSERT INTO os_core_faqanswer VALUES (21,4,'Auf welcher PostNuke-Version basiert OpenStar?','Der aktuelle OpenStar Release (4.02) basiert auf PostNuke 0.762 und ist kompatibel zu dieser PostNuke-Version.','2');
INSERT INTO os_core_faqanswer VALUES (22,4,'Wird OpenStar zukünftige PostNuke Versionen unterstützen?','Ja. Wir planen, um OpenStar innerhalb von ein paar Wochen auf die neueste stabile PostNukeVersion upzugraden, vorausgesetzt, dass diese Version sich in der Praxis als stabil erweist.','2');
INSERT INTO os_core_faqanswer VALUES (23,4,'Was sind die auffallendsten Veränderungen für Benutzer?','Wir haben PostNuke mit den folgenden Funktionalitäten erweitert: \r\n<ul>\r\n<li>Kalender und Adressbuch (integriert)</li>\r\n<li>Medien- und Contentmanagement(integriert)</li>\r\n<li>Projekt Management</li>\r\n<li>Event- und Ressourcenbuchungssystem</li>\r\n<li>Helpdesk und Service</li>\r\n<li>und einiges mehr ...</li>\r\n</ul>\r\nSie sollten OpenStar als ein kompletteres PostNuke sehen: Die bewährte PostNuke Basis mit nützlichen, externen Modulen schon eingebunden und konfiguriert. ','2');
INSERT INTO os_core_faqanswer VALUES (24,4,'Was sind die auffallendsten Veränderungen für Entwickler?','Wir liefern ein Entwicklungs-Kit (API), welches die folgenden (Entwicklungs-)Tätigkeiten signifikant vereinfacht: \r\n<ul>\r\n<li><a href=\"index.php?module=pagesetter&func=viewpub&tid=2&pid=14&mp=/Entwickler/Objekt%20Layer\">Objekt Persistenz Layer</a></li>\r\n<li><a href=\"index.php?module=pagesetter&func=viewpub&tid=2&pid=15&mp=/Entwickler/Komponenten\">Objekt Komponent Architektur</a></li>\r\n<li><a href=\"index.php?module=pagesetter&func=viewpub&tid=2&pid=16&mp=/Entwickler/Erweiterungen\">Integration von weiteren externen Komponenten<a/></li>\r\n</ul>\r\nModulentwicklung unter Verwendung dieser Tools/Methodologien ist signifikant schneller als Modulentwicklung in der Standard-PostNuke-Umgebung.  ','2');
INSERT INTO os_core_faqanswer VALUES (25,4,'Was kostet mich der Spaß? Unter welcher Lizenz wird der Code vertrieben?','Unsere Software ist gratis und wird unter der GNU GPL Lizenz vertrieben. Gemäß dieser Lizenz ist die Software frei und gratis und kann zu den Bedingungen der GNU GPL durch Dritte ohne Einschränkungen verwendet werden. Dies bedeutet auch, daß Module auf der Basis der v4blib GPL lizenziert sein müssen.','2');
INSERT INTO os_core_faqanswer VALUES (26,4,'Warum eine neue Distribution (anstatt PostNuke zu verbessern)? Arbeitet Ihr mit dem PostNuke Team zusammen?','Da PostNuke sich zum Ziel gesetzt hat eine kleine, stabile Core-Engine zu erzeugen, sind manche unserer Änderungen zu weitreichend, um in den PostNuke Core aufgenommen zu werden. Wo es Sinn macht, geben wir gezielte Fixes und Patches an das PostNuke-Team weiter. Wir möchten hier nochmals darauf hinweisen dass wir absolut <i>keinen Fork von PostNuke machen/erreichen wollen</i> sondern weiterhin auf die bewährte PostNuke Core Engine aufsetzen werden. Wir haben viel Zeit und Mühe darauf verwendet um OpenStar 100% kompatibel zu PostNuke zu halten und werden dies auch weiterhin tun. Sie können einige der Ideen die zur Erstellung von OpenStar geführt haben auf den Seiten ab <a href=\"index.php?module=pagesetter&func=viewpub&tid=2&pid=0&mp=/OpenStar/Hintergrund\">hier</a> nachlesen.','2');
INSERT INTO os_core_faqanswer VALUES (27,4,'Funktioniert Eure Entwicklungsbibliothek wie beschrieben oder ist das Ganze nur eine neue/experimentelle Idee?','Unsere Entwicklungsbibliotheken und Komponenten (genannt v4blib) sind das Resultat der Erfahrungen die wir mit der Implementierung von neuen Module für unsere Kunden gesammelt haben. Wir haben diese Tools seit mehr als einem Jahr im Einsatz und sind auf keine nennenswerten Probleme gestoßen. Da diese Komponenten schon seit längerer Zeit eingesetzt werden, können Sie davon ausgehen, daß sie relativ Fehlerfrei sind und dass es bei den bestehenden Interfaces keine nennenswerten Änderungen mehr geben wird.','2');
INSERT INTO os_core_faqanswer VALUES (28,4,'Wie kann ich damit anfangen die OpenStar development libraries für meine Module zu verwenden?','Als Erstes, sehen Sie sich bitte die <a href=\"index.php?module=pagesetter&func=viewpub&tid=2&pid=4&mp=/Entwickler\">Entwickler</a> Abteilung unserer Site an. Hier finden Sie eine Übersicht der Features, die unsere Library zur Verfügung stellt sowie die automatisch generierte Dokumentation (diese ist auch im <i>includes/v4blib/html</i> Verzeichnis der OpenStar Distribution enthalten). Falls Sie sich nach dieser Lektüre immer noch nicht sicher sind, sind Sie herzlich willkommen, um im <a href=\"index.php?module=pnForum&func=viewforum&forum=4&mp=/Forum\">Development Forum</a> weitere spezifische Fragen zu stellen.','2');
INSERT INTO os_core_faqanswer VALUES (29,4,'Welche Sprachen unterstützt OpenStar?','Wir liefern OpenStar mit komplettem Sprachsupport für Deutsch und Englisch. Manche Module, die von der PostNuke community unterstützt werden enthalten eventuell noch zusätzliche Übersetzungen.','2');
INSERT INTO os_core_faqanswer VALUES (30,4,'Wie kann ich Unterstützung für eine weitere Sprache hinzufügen?','Zuerst müssen Sie das PostNuke Sprachpacket für Ihre (neue) Sprache herunterladen und installieren. Dann müssen Sie die Übersetzungspackete für die PostNuke module der Drittanbieter die wir mitliefern finden und installieren. Zuletzt müssen Sie die Sprachdateien der v4b Module für Ihren neue Sprache übersetzen. Dies ist sicherlich mit einigem Arbeitsaufwand verbunden was sich jedoch leider nicht vermeiden lässt. Wen Sie mit uns Kontakt über das Forum aufnehmen, werden wir Sie so gut wie möglich bei dieser Tätigkeit unterstützen.','2');
INSERT INTO os_core_faqanswer VALUES (31,4,'Wie weiss ich ob ein Modul spezifisch für die OpenStar Architektur ist oder ob es sich um ein standard PostNuke Module handelt?','Falls ein Modulename mit \"v4b\" anfängt wurde es durch uns geschrieben und verwendet die Features unsere Entwicklungsbibliothek (v4blib). Bei allen anderen Modulen können Sie davon ausgehen dass es sich um module handelt die für die allgemeine PostNuke Plattform geschrieben wurden.','2');
INSERT INTO os_core_faqanswer VALUES (40,2,'How should I install Open-Star?','The <i>first</i> thing you should do, is read the file <i>openstar/README_openstar.txt</i> before doing anything at all.\r\n\r\nThe recommended installation procedure for OpenStar is to import the file\r\n<pre>        openstar/includes/v4blib/extra/openstar_ship.sql</pre>This will give you an OpenStar instance with all new functionality installed including a properly populated menu.  Using this approach you do not have all the options that the default PostNuke install gives you (you can, for example, not choose your table prefix and initial account/password) but you get a properly initialized database which is probably the fastest way to give you a properly configured instance. \r\n\r\nYou can import the sqlfiles by doing a\r\n<pre>        mysql -D [database] -u [database_user] -p <  openstar_ship.sql</pre>Please note that when you import the default OpenStar schema, the default table prefix (as specified in config.php) for the delivered OpenStar tables is <i>os_core</i> and the default admin password is <i>admin</i>.\r\n\r\nPlease note that you need to perform post-installation steps (as detailed below).\r\n','2');
INSERT INTO os_core_faqanswer VALUES (41,2,'Do I need to perform any post-installation steps? ','Yes! Once you have installed the files and loaded the database data you can call the script \r\n<pre>        http://[server]/[openstar_install_dir]/openstar_postinstall.php</pre>This script will apply the required changes to config.php and set the proper path for the photoshare module.','2');
INSERT INTO os_core_faqanswer VALUES (42,2,'Can I install OpenStar using the standard PostNuke methodology?','You can choose to install OpenStar as you would any standard PostNuke distribution. In order to do so, you first need to enable the installer by renaming <i>install.bak</i> to <i>install</i> and <i>install.php.bak</i> to <i>install.php</i> and then hit <i>http://[server]/[openstar_install_dir]/openstar/install.php</i> and proceed from there. This will give you the basic PostNuke install/configuration with all extra modules disabled. The task of activating these modules and further populating and configuring your system is then up to you. <i>Be warned</i>: this is a somewhat tedious task which is not fully documented.','2');
INSERT INTO os_core_faqanswer VALUES (43,2,'What about some basic demo data?','The OpenStar download contains the necessary files and data to supply a minimal demo environment. If you want an installation without any demo data, you can load the \r\n<pre>        openstar/includes/v4blib/extra/openstar_base.sql</pre> SQL-dump rather than the previously mentioned <i>openstar_ship.sql</i> file. Please note that if you do this, some of the links in the left menu (such as Content) will not work correctly as there\'s no demo data to display.','2');
INSERT INTO os_core_faqanswer VALUES (44,2,'What extra configuration files does OpenStar use? ','OpenStar uses the <i>personal_config.php</i> file to store OpenStar-specific configuration data. Please note that while this file can be modified, this should only be done if you know what you\'re doing as it can have  a significant impact on your site/installation.  ','2');
INSERT INTO os_core_faqanswer VALUES (45,2,'Can I install additional PostNuke modules onto OpenStar?','Absolutely! OpenStar, while an extension to the PostNuke framework, remains compatible with the basic PostNuke distribution. If your module works on a standard 0.750 PostNuke installation, it should work with OpenStar. If you run into problems, please report them in the <a href=\"index.php?module=pnForum&func=viewforum&forum=3&mp=/Forum\">Support Forum</a> and we will do our best to help you out.','2');
INSERT INTO os_core_faqanswer VALUES (46,2,'Is OpenStar PHP5 compatible?','Yes. We have tested OpenStar under PHP5 and applied selective fixes in order to ensure that it works under PHP5 without problems.','2');
INSERT INTO os_core_faqanswer VALUES (60,5,'Wie sollte ich Open-Star installieren?','Das <i>Erste</i> was Sie tun sollten ist, die Datei  <i>openstar/README_openstar.txt</i> lesen. Die einfachste Art und Weise OpenStar zu installieren, ist die Datei<pre>        openstar/includes/v4blib/extra/openstar_ship.sql</pre> zu importieren. Dies erstellt Ihnen eine vollständig konfigurierte Instanz von OpenStar, welche allerdings nicht die detaillierten PostNuke Installations/Konfiguratsmöglichkeiten beinhaltet. Sie können diese Dump-Dateien folgendermaßen importieren:\r\n<pre>        mysql -D [datenbank] -u [benutzer] -p < openstar_ship.sql</pre>Bitte beachten Sie, daß das Tabellen-prefix für das OpenStar Schema (wie in config.php spezifiziert) <i>os_core</i>, und das voreingestellte Admin Paßwort <i>admin</i> ist.','2');
INSERT INTO os_core_faqanswer VALUES (61,5,'Muss ich noch irgendwelche Nach-Installations-Tätigkeiten ausführen?','Ja! Sobald die Dateien aufgespielt und die Datenbank eingerichtet ist, sollten Sie das Script \r\n<pre>        http://[server]/[openstar_install_dir]/openstar_postinstall.php</pre>aufrufen. Dieses Script nimmt die notwendigen Änderungen innerhalb der config.php vor und passt in der Datenbank die Pfade für das Modul photoshare an.','2');
INSERT INTO os_core_faqanswer VALUES (62,5,'Kann ich OpenStar auf die normale PostNuke Art und Weise installieren?','Für die Installation von OpenStar können Sie verfahren wie bei einer Standard PostNuke Anwendung. Um dies zu tun, müssen folgende Verzeichnisse umbenannt werden: <i>install.bak</i> nach <i>install</i> und <i>install.php.bak</i> nach <i>install.php</i>. Danach bitte <i>http://[server]/[openstar_install_dir]/openstar/install.php</i> im Browser aufrufen und von dieser Stelle aus weiter fortfahren. Damit erhalten Sie PostNuke in seiner Grundversion, ohne dass die zusätzlichen, OpenStar spezifischen Funktionen aktiviert sind. Der Prozeß, die zusätzliche Funktionen zu aktivieren und die Konfiguration Ihres Systems bleiben Ihnen überlassen. <i>Seien Sie gewarnt</i>: es ist ein nicht ganz so einfacher Weg, der nicht vollständig dokumentiert ist. ','2');
INSERT INTO os_core_faqanswer VALUES (63,5,'Gibt es auch ein paar Demo-Daten?','Der OpenStar Download enthält die benötigten Files und Daten, um eine minimale Demo-Umgebung einzurichten. Falls Sie eine Installation ohne jegliche Demo Daten möchten, könne Sie den SQL-Dump\r\n<pre>        openstar/includes/v4blib/extra/openstar_base.sql</pre> anstatt des zuvor genannten <i>openstar_ship.sql</i> Dump importieren.','2');
INSERT INTO os_core_faqanswer VALUES (64,5,'Welche weiteren Konfigurationsdateien verwendet OpenStar? ','OpenStar verwendet die <i>personal_config.php</i> Datei um OpenStar-eigene Konfigurations-Settings zu verwalten. Bitte beachten Sie, dass während grundsätzlich Konfigurationsänderungen an dieser Datei vorgenommen werden könnnen, dies nur getan werden sollte, wenn Sie wissen was Sie tun, da dies zu signifikanten Änderungen an Ihrer Site/Installation führen kann.','2');
INSERT INTO os_core_faqanswer VALUES (65,5,'Kann ich weitere PostNuke Module unter OpenStar installieren?','Natürlich! Obwohl OpenStar eine Erweiterung des PostNuke Frameworks ist, bleibt es kompatibel zum PostNuke Basispacket. Falls Ihr Modul unter der normalen PostNuke 0.750 Version läuft, sollte es auch unter OpenStar funktionieren. Falls Sie hierbei Probleme haben, melden Sie diese bitte im <a href=\"index.php?module=pnForum&func=viewforum&forum=3&mp=/Forum\">Support Forum</a> und wir werden unser Möglichstes tun, um Ihnen zu helfen.','2');
INSERT INTO os_core_faqanswer VALUES (66,5,'Ist OpenStar PHP5 kompatibel?','Ja. Wir haben OpenStar unter PHP5 getestet und selective Fixes angebracht um sicherzustellen daß OpenStar problemlos unter PHP5 läuft.','2');

--
-- Table structure for table `os_core_faqcategories`
--

DROP TABLE IF EXISTS os_core_faqcategories;
CREATE TABLE os_core_faqcategories (
  pn_id_cat int(6) NOT NULL auto_increment,
  pn_categories varchar(255) default NULL,
  pn_language varchar(30) NOT NULL default '',
  pn_parent_id int(6) NOT NULL default '0',
  PRIMARY KEY  (pn_id_cat)
) TYPE=MyISAM;

--
-- Dumping data for table `os_core_faqcategories`
--

INSERT INTO os_core_faqcategories VALUES (1,'OpenStar','eng',0);
INSERT INTO os_core_faqcategories VALUES (2,'Installation & Configuration','eng',1);
INSERT INTO os_core_faqcategories VALUES (3,'Daily Site Management','eng',1);
INSERT INTO os_core_faqcategories VALUES (4,'OpenStar','deu',0);
INSERT INTO os_core_faqcategories VALUES (5,'Installation & Konfiguration','deu',4);
INSERT INTO os_core_faqcategories VALUES (6,'Täglicher Betrieb','deu',4);

