<?php

// 
// Chaines v4blib en français
// 

define('_V4B_TEXT_ALL','Tout');
define('_V4B_TEXT_YES','Oui');
define('_V4B_TEXT_NO','Non');
define('_V4B_TEXT_PERMISSION_PRIVATE','Privé');
define('_V4B_TEXT_PERMISSION_GROUP','Groupe');
define('_V4B_TEXT_PERMISSION_PUBLIC','Public');
define('_V4B_TEXT_PERMISSION_LEVEL_NONE','Aucun');
define('_V4B_TEXT_PERMISSION_LEVEL_READ','Lecture');
define('_V4B_TEXT_PERMISSION_LEVEL_WRITE','Ecriture');
define('_V4B_TEXT_PERMISSION_BASIC_PUBLIC','Public');
define('_V4B_TEXT_PERMISSION_BASIC_PRIVATE','Privé');
define('_V4B_TEXT_PERMISSION_BASIC_GROUP','Groupe');
define('_V4B_TEXT_PERMISSION_BASIC_USER','Utilisateur');

?>
