<?php

// 
// German v4blib strings
// 

define('_V4B_TEXT_ALL', 			'Alle');
define('_V4B_TEXT_YES', 			'Ja');
define('_V4B_TEXT_NO', 				'Nein');
define('_V4B_TEXT_PERMISSION_PRIVATE', 		'Privat');
define('_V4B_TEXT_PERMISSION_GROUP', 		'Gruppe');
define('_V4B_TEXT_PERMISSION_PUBLIC', 		'Öffentlich');
define('_V4B_TEXT_PERMISSION_LEVEL_NONE', 	'Keine');
define('_V4B_TEXT_PERMISSION_LEVEL_READ',	'Lesen');
define('_V4B_TEXT_PERMISSION_LEVEL_WRITE', 	'Schreiben');

?>
