<?php

// 
// English v4blib strings
// 

define('_V4B_TEXT_ALL', 			'All');
define('_V4B_TEXT_YES', 			'Yes');
define('_V4B_TEXT_NO', 				'No');
define('_V4B_TEXT_PERMISSION_PRIVATE', 		'Private');
define('_V4B_TEXT_PERMISSION_GROUP', 		'Group');
define('_V4B_TEXT_PERMISSION_PUBLIC', 		'Public');
define('_V4B_TEXT_PERMISSION_LEVEL_NONE', 	'None');
define('_V4B_TEXT_PERMISSION_LEVEL_READ',	'Read');
define('_V4B_TEXT_PERMISSION_LEVEL_WRITE', 	'Write');

?>
