<?php
/**
 * PostNuke Application Framework
 *
 * @copyright (c) 2004, PostNuke Development Team
 * @link http://www.postnuke.com
 * @version $Id: display.php 30 2007-11-20 09:04:36Z markwest $
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @author Andrea Moro
 * @author Mark West
 * @package PostNuke_3rdParty_Modules
 * @subpackage htmlpages
 */

/**
 * display item
 * This is a standard function to provide detailed informtion on a single item
 * available from the module.
 */
function htmlpages_user_display($args)
{
    list($pid,$title) = pnVarCleanFromInput('pid', 'title');

    extract($args);

    if (!empty($objectid)) {
        $pid = $objectid;
    }
    if (!isset($pid)) {
        return pnVarPrepHTMLDisplay(_HTMLPAGESPIDNOTINDICATED);
    }

    // Create output object
	$pnRender = new pnRender('htmlpages');

	// Use the page id as the cache id
	$pnRender->cache_id = $pid;

	// check out if the contents are cached.
	if ($pnRender->is_cached('htmlpages_user_display.htm')) {
	   return $pnRender->fetch('htmlpages_user_display.htm');
	}
		
    // get the page
    $item = pnModAPIFunc('htmlpages', 'user', 'get', array('pid' => $pid, 'parse' => true));

    if (!pnSecAuthAction(0, 'htmlpages::', "$item[title]::$pid", ACCESS_READ)) {
        return pnVarPrepHTMLDisplay(_MODULENOAUTH);
    }

    if ($item == false) {
        return pnVarPrepHTMLDisplay(_HTMLPAGESITEMFAILED);
    }

    // set the page title
    // a quick hack based on .7x news module
    // TODO move to page vars under .8x
    // LDH don't show the H1 title on the rendered page (save space & eliminate redundancy)
    $item['title'] = "" ;
	$GLOBALS['info']['title'] = $item['title'];

	$pnRender->assign($item);
	
    // Return the output that has been generated by this function
	return $pnRender->fetch('htmlpages_user_display.htm');
}