<?php
/**
 * PostNuke Application Framework
 *
 * @copyright (c) 2004, PostNuke Development Team
 * @link http://www.postnuke.com
 * @version $Id: modify.php 30 2007-11-20 09:04:36Z markwest $
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @author Andrea Moro
 * @author Mark West
 * @package PostNuke_3rdParty_Modules
 * @subpackage htmlpages
 */

/**
 * modify an item
 * This is a standard function that is called whenever an administrator
 * wishes to modify a current module item
 * @param 'pid' the id of the item to be modified
 */
function htmlpages_admin_modify($args)
{
    // Get parameters from whatever input we need.
    list($pid, $objectid)= pnVarCleanFromInput('pid', 'objectid');
    extract($args);
    
    if (!empty($objectid)) {
        $pid = $objectid;
    }

    // The user API function is called.  
    $item = pnModAPIFunc('htmlpages', 'user', 'get', array('pid' => $pid));

    if ($item == false) {
        pnSessionSetVar('errormsg', _HTMLPAGESNOSUCHITEM);
        return false;
    }

    if (!pnSecAuthAction(0, 'htmlpages::', "$item[title]::$pid", ACCESS_EDIT)) {
        pnSessionSetVar('errornsg', _MODULENOAUTH.$item['title'].$pid);
        return false;
    }

	// create new output object
	$pnRender = new pnRender('htmlpages');

    // As Admin output changes often, we do not want caching.
    $pnRender->caching = false;

	// assign the item id
    $pnRender->assign('pid', $pid);

	// assign the item
	$pnRender->assign($item);

    // only admins can change userid's
    if (pnSecAuthAction(0, 'htmlpages::', "$item[title]::$pid", ACCESS_ADMIN)) {  
		$pnRender->assign('adminacccess', true);
    } else {
		$pnRender->assign('adminacccess', false);
    }
	
    // Return the output that has been generated by this function
    return $pnRender->fetch('htmlpages_admin_modify.htm');
}
