<?php /* Smarty version 2.6.14, created on 2007-10-22 16:36:03
         compiled from Volunteer-full.html */

$this->_cache_serials['pnTemp/pnRender_compiled\pagesetter^dpXanXPStyleSilver^eng^%%17^178^1783600F%%Volunteer-full.html.inc'] = '660eb7472217c3afc40b2b9dfae0a5de';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'nocache', 'Volunteer-full.html', 11, false),array('function', 'pnmodurl', 'Volunteer-full.html', 15, false),array('function', 'pnmodcallhooks', 'Volunteer-full.html', 16, false),)), $this); ?>
<?php
function _smarty_tplfunc_660eb7472217c3afc40b2b9dfae0a5de_0(&$_smarty)
{
$_smarty->_tag_stack[] = array('nocache', array()); $_block_repeat=true;pnRender_block_nocache($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], null, $_smarty, $_block_repeat);while ($_block_repeat) { ob_start();  echo $_smarty->_tpl_vars['core']['hitCount'];  $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo pnRender_block_nocache($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], $_block_content, $_smarty, $_block_repeat); }  array_pop($_smarty->_tag_stack); 
}


function _smarty_tplfunc_660eb7472217c3afc40b2b9dfae0a5de_1(&$_smarty)
{
$_smarty->_tag_stack[] = array('nocache', array()); $_block_repeat=true;pnRender_block_nocache($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], null, $_smarty, $_block_repeat);while ($_block_repeat) { ob_start();  echo $_smarty->_tpl_vars['core']['editThis'];  $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo pnRender_block_nocache($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], $_block_content, $_smarty, $_block_repeat); }  array_pop($_smarty->_tag_stack); 
}



?>
